# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8ea74513fa3b8c7b099883a83444ba8a4236f16b85d566bc0273c8dcd847a53c9a962c98175865c9770d00c177750c250dee4e823a29b5b5c8b679e526098d9

test:
  secret_key_base: 86f7b7e2c8343943ce4dffbfdaf4ae73467d2d8cd7c46ca3ea2f8f8f89782ad7a53d5819b14d28a539ed4c3701070184a525a7b124c21e3048d3d0132387b01d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
