source "https://rubygems.org"
ruby "2.2.0"

group :development, :test do
  gem "byebug", "~> 3.5"
  gem "web-console", "~> 2.0"
  gem "spring", "~> 1.2"
end

gem "rails", "~> 4.2"
gem "pg", "~> 0.18"
gem "rails_12factor", "~> 0.0", {:group=>:production}
gem "thin", "~> 1.6"
gem "bootstrap-sass", "~> 3.3.3"
gem "sass-rails", "~> 5.0"
gem "uglifier", "~> 2.7"
gem "coffee-rails", "~> 4.1"
gem "jquery-rails", "~> 4.0"
gem "turbolinks", "~> 2.5"
gem "jbuilder", "~> 2.2"
gem "sdoc", "~> 0.4", {:group=>:doc}
